Title: To review or not to review? That's the question
Team members: 
[Doria Wengting Wang](https://github.com/DoriaWW), [Inge Oostveen](https://github.com/IngeOostveen), [Ralph Delsing](https://github.com/RalphGit21), [Paulus Hovens](https://github.com/pphovens), [Wouter Floors](https://github.com/WouterFloors)

abstract:


bibliography: references.bib
output: pdf_document
header-includes: 
- \usepackage{booktabs}

---

```{r, echo = FALSE}
library(rlist)
library(modelsummary)
```

# Introduction

# Motivation

We all know the feeling of opening an e-mail that asks you to leave a review on a product that you just bought or a listing that you stayed the night at. But do more reviews lead to a higher review score? Furthermore, this effect is examined at cities in Spain that differ in sizes, such as Malaga compared to the capital Madrid. This code is written in order to find answers to these questions.

The reason for diving into this problem is because review scores are an important factor for customers when they decide which listing to stay at. Hosts want a good review score and some push their guests to leave a review. The issue that arises is that more reviews does not necessarily result into a higher review score. This study is conducted in order to show hosts if they should or should not push their guests for reviews by analyzing the relationship between review score and number of reviews, while taking moderators and control variables into account.

The study focusses on seven different cities in Spain. To be able to examine the differences between small and big cities, there are three categories; Big, Medium or Small. The number of residents determine the category of the city:

A Big city has more than 1000000 (a million) residents
A Medium city has more than 500000 residents
A Small city has less than 500000 residents
The cities:

Big: Barcelona and Madrid

Medium: Sevilla, Valencia and Malaga

Small: Menorca and Girona


# Data

# Part I. Votes
## Data Collection


## Data Processing



# Methodology




## Compare differences in difference (DiD)



# Results

(Put the regression model here)

From the regression model, the individual outputs for the moderators are interpreted:

Moderator 1: The predicted rating including only the first moderator, host_is_superhost becomes: rating = 4.272 + .387 x host_is_superhost + .0015 x nr_of_reviews - .0013 x host_is_superhost x nr_of_reviews. If the host of a listing is a superhost, this variable is coded as a "1". Thus, the rating for a superhost is 4.272 + .387 + nr_of_reviews x (.0015 - .0013) = 4.659 + .0002 * nr_of_reviews, whereas the rating of a listing from someone who is not a superhost is 4.272 + .0015 x nr_of_reviews. Despite the interaction effect being negative (-.0013), the predicted ratings for superhosts are clearly higher. Moreover, this effect is highly significant (p<.01)

Moderator 2: For the second moderator, room_type, the results are statistically insignificant (p=.95, p=.34, p=.83). Thus, no further work is needed on this moderator, as this moderator does not influence the relationship between the rating and the number of reviews.

Moderator 3: Finally, the last moderator includes the city size. As for moderator 1, these interaction effects are highly significant (p<.01). The predicted rating including this moderator is as follows: 4.272 + .0015 x nr_of_reviews + .037 x size_small + .072 x size_medium + .0007 x nr_of_reviews x size_small - .0003 x nr_of_reviews * size_medium. From the output based on the moderators implemented as independent variables, it can be seen that they are significantly larger than for the base level (which is size_large). Thus, these small and medium sized cities are rated significantly higher than larger cities. However, looking at the interaction effects for these two columns, despite being statistically significant, are so small (.0007 and -.0003) that they only influence the relationship between the rating and number of reviews minimally. 



# Conclusion


## Managerial Relevance


# Word Count {-}

Number of Words:

# References


# Appendix
